// lib/email/sendRepEmail.ts

import { Resend } from "resend";
import type { QuizSubmission } from "@/lib/schemas/quiz";
import type { NormalizedBookingData } from "@/lib/schemas/bookingWebhook";

// Lazy initialization of Resend client
let resendClient: Resend | null = null;

function getResendClient(): Resend {
  if (!resendClient) {
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      throw new Error("RESEND_API_KEY environment variable is not set");
    }
    resendClient = new Resend(apiKey);
  }
  return resendClient;
}

/**
 * Format a date string for display
 */
function formatDateTime(isoString: string, timezone: string): string {
  try {
    const date = new Date(isoString);
    return date.toLocaleString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
      timeZone: timezone,
      timeZoneName: "short",
    });
  } catch {
    return isoString;
  }
}

/**
 * Format quiz answers for email display
 */
function formatQuizAnswers(submission: QuizSubmission): string {
  const lines: string[] = [];

  lines.push(`Name: ${submission.name}`);
  lines.push("");
  lines.push(`Energy Level: ${submission.energyLevel}/10`);
  lines.push(`Crashes after lunch: ${submission.crashAfterLunch ? "Yes" : "No"}`);
  lines.push(`Difficulty waking: ${submission.difficultyWaking ? "Yes" : "No"}`);

  if (submission.wakeAtNight.wakes) {
    const reasons = submission.wakeAtNight.reasons?.length
      ? submission.wakeAtNight.reasons
          .map((r) => {
            switch (r) {
              case "eat": return "to eat";
              case "drink": return "to drink";
              case "pee": return "to urinate";
              case "no_reason": return "no apparent reason";
            }
          })
          .join(", ")
      : "reasons not specified";
    lines.push(`Wakes at night: Yes (${reasons})`);
  } else {
    lines.push(`Wakes at night: No`);
  }

  lines.push(`Brain fog: ${submission.brainFog ? "Yes" : "No"}`);

  if (submission.bowelIssues.length > 0) {
    const issues = submission.bowelIssues
      .map((i) => {
        switch (i) {
          case "straining": return "straining";
          case "pain": return "pain";
          case "incomplete": return "incomplete emptying";
          case "diarrhea": return "diarrhea";
          case "smell": return "excessive smell/mess";
        }
      })
      .join(", ");
    lines.push(`Bowel issues: ${issues}`);
  } else {
    lines.push(`Bowel issues: None`);
  }

  lines.push(`Cold extremities: ${submission.coldExtremities ? "Yes" : "No"}`);
  lines.push(`White tongue coating: ${submission.whiteTongue ? "Yes" : "No"}`);
  lines.push("");
  lines.push(`Typical eating:\n${submission.typicalEating}`);
  lines.push("");
  lines.push(`Health goals:\n${submission.healthGoals}`);

  return lines.join("\n");
}

/**
 * Build the email body
 */
function buildEmailBody(params: {
  payload: NormalizedBookingData;
  submission: QuizSubmission | null;
  assessment: string | null;
}): string {
  const { payload, submission, assessment } = params;
  const { booking, client, rep, appointmentType } = payload;

  const sections: string[] = [];

  // Booking details section
  sections.push("═══════════════════════════════════════════════════════════");
  sections.push("BOOKING DETAILS");
  sections.push("═══════════════════════════════════════════════════════════");
  sections.push("");
  sections.push(`Client: ${client.firstName} ${client.lastName}`);
  sections.push(`Email: ${client.email}`);
  if (client.phone) {
    sections.push(`Phone: ${client.phone}`);
  }
  sections.push(`Appointment: ${appointmentType}`);
  sections.push(`Time: ${formatDateTime(booking.startsAt, booking.timezone)}`);
  sections.push(`Assigned To: ${rep.name}`);

  // Quiz responses section (if available)
  if (submission) {
    sections.push("");
    sections.push("═══════════════════════════════════════════════════════════");
    sections.push("QUIZ RESPONSES");
    sections.push("═══════════════════════════════════════════════════════════");
    sections.push("");
    sections.push(formatQuizAnswers(submission));
  }

  // AI Assessment section (if available)
  if (assessment) {
    sections.push("");
    sections.push("═══════════════════════════════════════════════════════════");
    sections.push("AI ASSESSMENT");
    sections.push("═══════════════════════════════════════════════════════════");
    sections.push("");
    sections.push(assessment);
  }

  // Footer
  sections.push("");
  sections.push("───────────────────────────────────────────────────────────");
  sections.push("This email was automatically generated by Prism Quiz System");

  return sections.join("\n");
}

export interface SendRepEmailParams {
  payload: NormalizedBookingData;
  submission: QuizSubmission | null;
  assessment: string | null;
}

/**
 * Send email to the assigned rep with booking and quiz details
 */
export async function sendRepEmail(params: SendRepEmailParams): Promise<void> {
  const { payload, submission, assessment } = params;
  const { client, rep } = payload;

  const resend = getResendClient();

  const subject = `New Quiz Booking: ${client.firstName} ${client.lastName}`;
  const body = buildEmailBody({ payload, submission, assessment });

  // Default to Resend test address if no FROM address configured
  const fromAddress = process.env.RESEND_FROM_ADDRESS || "Prism Quiz <onboarding@resend.dev>";

  const { error } = await resend.emails.send({
    from: fromAddress,
    to: rep.email,
    subject,
    text: body,
  });

  if (error) {
    console.error("[Rep Email] Send failed:", error);
    throw new Error(`Failed to send email: ${error.message}`);
  }

  console.log(`[Rep Email] Sent to ${rep.email} for client ${client.email}`);
}
